  main = ".open-next/worker.js"
  name = "another1"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  
  # D1 Database configuration
  [[d1_databases]]
  binding = "DB"
  database_name = "contact-us"
  database_id = "526e1010-cbde-472c-9712-a29913adddf8"
  
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"

